title: borelli.blog # name of the site
author: Luan Borelli # name of site's author
email: contato@luanborelli.net # email of site's author
url: https://borelli.blog # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A deliberately unorganized, highly personal blog where I write for myself and hoard whatever interests me. Posts are in English and Portuguese; Portuguese posts are mostly about Brazil-related topics. <br> <br> For daily commentary on Brazil (in Portuguese), follow my <a href="https://x.com/BorelliLuan" target="_blank">Brazilian X profile</a>. For academic commentary and work, follow my <a href="https://x.com/BorelliEcon" target="_blank">academic X profile</a> or visit my <a href="https://luanborelli.com/" target="_blank">academic website</a>. 

permalink: /:slug.html

favicon: "library.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
